# Generated by Django 4.1.7 on 2023-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yellowpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=20)),
                ('ContactNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
